-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Users"
(
    "User_id" integer,
    username "char" NOT NULL,
    created date,
    PRIMARY KEY ("User_id")
);

CREATE TABLE IF NOT EXISTS public."Photos"
(
    "Photo_id" integer,
    image_url "char",
    "User_id" integer,
    publication_date date,
    PRIMARY KEY ("Photo_id")
);

CREATE TABLE IF NOT EXISTS public."Likes"
(
    "User_id" integer,
    "Photo_id" integer NOT NULL,
    date_oflike date,
    PRIMARY KEY ("User_id", "Photo_id")
);

CREATE TABLE IF NOT EXISTS public.follow
(
    follower_id integer,
    followee_id integer,
    date_and_time timestamp without time zone,
    PRIMARY KEY (follower_id, followee_id)
);

ALTER TABLE IF EXISTS public."Photos"
    ADD CONSTRAINT "User_id" FOREIGN KEY ("User_id")
    REFERENCES public."Users" ("User_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Likes"
    ADD CONSTRAINT "Photo_id" FOREIGN KEY ("Photo_id")
    REFERENCES public."Photos" ("Photo_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.follow
    ADD CONSTRAINT follower_id FOREIGN KEY (follower_id)
    REFERENCES public."Users" ("User_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.follow
    ADD CONSTRAINT followee_id FOREIGN KEY (followee_id)
    REFERENCES public."Users" ("User_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;